sudo: false

services:
- postgresql

addons:
  postgresql: 9.4

env:
  global:
      DB_HOST: localhost
      DB_PASS:
      DB_USER: postgres
      DB_POST: 5432

install:
- cd backend && npm install && cd ..

before_script:
- psql -c 'create database roomease_test;' -U postgres

script:
- cd backend && npm test

language: node_js

node_js:
- "8.9.1"